# Generated by Django 5.2.15 on 2026-07-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_bridge', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('intrusion', '入侵'), ('fall', '跌倒'), ('fight', '鬥毆'), ('fire', '火煙'), ('abnormal', '異常行為')], max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('new', '新事件'), ('reviewing', '確認中'), ('confirmed', '已確認'), ('false_alarm', '誤報'), ('notified', '已通報'), ('closed', '已結案')], default='new', max_length=50)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('description', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ai_bridge.aimodel')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
