# Generated by Django 5.2.15 on 2026-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('intrusion', 'Intrusion'), ('fall', 'Fall'), ('fight', 'Fight'), ('fire', 'Fire'), ('abnormal', 'Abnormal Behavior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('confirmed', 'Confirmed'), ('false_alarm', 'False Alarm'), ('notified', 'Notified'), ('closed', 'Closed')], default='new', max_length=50),
        ),
    ]
