# Generated by Django 5.2.15 on 2026-07-02 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0002_alter_aimodel_options_alter_aimodel_api_url_and_more'),
        ('cameras', '0001_initial'),
        ('events', '0002_alter_event_event_type_alter_event_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-detected_at', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ai_bridge.aimodel', verbose_name='AI 模型'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera', verbose_name='攝影機'),
        ),
        migrations.AlterField(
            model_name='event',
            name='confidence',
            field=models.FloatField(default=0.0, verbose_name='信心分數'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='事件說明'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='偵測時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('escalator_fall', '電扶梯人員跌倒'), ('luggage_roll', '大行李箱滾落'), ('large_luggage_intrusion', '大件行李進入設定畫面區域'), ('wheelchair_detected', '辨識輪椅'), ('passenger_loitering', '旅客逾時滯留'), ('crowd_count_abnormal', '人流統計異常'), ('other', '其他')], default='other', max_length=50, verbose_name='事件類型'),
        ),
        migrations.AlterField(
            model_name='event',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='event_snapshots/', verbose_name='事件截圖'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='處理狀態'),
        ),
        migrations.CreateModel(
            name='CrowdFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='人流數量')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否超出正常範圍')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='紀錄時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_flow_records', to='cameras.camera', verbose_name='攝影機')),
            ],
            options={
                'verbose_name': 'Crowd flow record',
                'verbose_name_plural': 'Crowd flow records',
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdFlowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='設定名稱')),
                ('min_count', models.PositiveIntegerField(default=0, verbose_name='人流下限')),
                ('max_count', models.PositiveIntegerField(default=100, verbose_name='人流上限')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_flow_settings', to='cameras.camera', verbose_name='攝影機')),
            ],
            options={
                'verbose_name': 'Crowd flow setting',
                'verbose_name_plural': 'Crowd flow settings',
                'ordering': ['id'],
            },
        ),
    ]
