# Generated by Django 5.2.15 on 2026-07-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0002_alter_aimodel_options_alter_aimodel_api_url_and_more'),
        ('cameras', '0002_camera_description_camera_status_and_more'),
        ('events', '0003_alter_event_options_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='severity',
            field=models.CharField(blank=True, db_index=True, default='', help_text='AI 推論主機回傳的事件嚴重程度。', max_length=30, verbose_name='事件嚴重程度'),
        ),
        migrations.AddField(
            model_name='event',
            name='snapshot_url',
            field=models.URLField(blank=True, default='', help_text='AI 推論主機提供的遠端事件快照網址。', max_length=1000, verbose_name='遠端快照 URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='外部 AI 推論主機所建立的事件識別碼。', max_length=100, null=True, verbose_name='來源事件 ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_host',
            field=models.CharField(blank=True, db_index=True, help_text='產生此事件的外部 AI 推論主機。', max_length=255, null=True, verbose_name='來源主機'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict, help_text='從 AI 推論主機取得的原始 JSON payload。', verbose_name='來源原始資料'),
        ),
        migrations.AlterField(
            model_name='crowdflowrecord',
            name='is_abnormal',
            field=models.BooleanField(default=False, verbose_name='是否異常'),
        ),
        migrations.AlterField(
            model_name='crowdflowsetting',
            name='max_count',
            field=models.PositiveIntegerField(default=100, verbose_name='最大人數'),
        ),
        migrations.AlterField(
            model_name='crowdflowsetting',
            name='min_count',
            field=models.PositiveIntegerField(default=0, verbose_name='最小人數'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('escalator_fall', '電扶梯跌倒'), ('luggage_roll', '行李滾落'), ('large_luggage_intrusion', '大型行李進入限制區域'), ('wheelchair_detected', '輪椅偵測'), ('passenger_loitering', '旅客逗留過久'), ('crowd_count_abnormal', '人流數量異常'), ('other', '其他')], default='other', max_length=50, verbose_name='事件類型'),
        ),
        migrations.AlterField(
            model_name='event',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='event_snapshots/', verbose_name='事件快照'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('source_host__isnull', False), ('source_event_id__isnull', False)), fields=('source_host', 'source_event_id'), name='unique_event_source_host_event_id'),
        ),
    ]
