# Generated by Django 5.2.15 on 2026-08-01 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0004_inferenceconnectionstate'),
        ('cameras', '0002_camera_description_camera_status_and_more'),
        ('events', '0005_localalarmpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, default='', max_length=100)),
                ('updated_fields', models.JSONField(blank=True, default=list)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_source_host_event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='ack_status',
            field=models.CharField(db_index=True, default='accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='camera_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='inference_host_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='mapping_status',
            field=models.CharField(db_index=True, default='resolved', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='station_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cameras.camera', verbose_name='攝影機'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('inference_host_code', ''), _negated=True), ('source_event_id__isnull', False)), fields=('inference_host_code', 'source_event_id'), name='unique_event_inference_host_source_id'),
        ),
        migrations.AddField(
            model_name='eventupdatelog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='events.event'),
        ),
    ]
