# Generated by Django 5.2.15 on 2026-08-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0003_occsyncstate_heartbeat_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceFaultLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("last_seen_at", models.DateTimeField(db_index=True)),
                (
                    "recovered_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("station_code", models.CharField(db_index=True, max_length=50)),
                ("station_name", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("camera", "Camera"),
                            ("inference_host", "Inference Host"),
                            ("speaker", "IP Speaker"),
                            ("notification_host", "Notification Host"),
                            ("occ_network", "OCC / Network"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("device_code", models.CharField(db_index=True, max_length=100)),
                ("device_name", models.CharField(max_length=150)),
                ("area", models.CharField(blank=True, max_length=150)),
                ("fault_code", models.CharField(db_index=True, max_length=100)),
                ("fault_description", models.CharField(max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("recovered", "Recovered")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["station_code", "status", "device_type"],
                        name="st_fault_station_status_idx",
                    ),
                    models.Index(
                        fields=["device_code", "fault_code", "status"],
                        name="st_fault_device_code_idx",
                    ),
                ],
            },
        ),
    ]
