# Generated by Django 5.2.15 on 2026-08-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0004_devicefaultlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceFaultChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("refreshed", "Refreshed"),
                            ("recovered", "Recovered"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("occurred_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("station_code", models.CharField(db_index=True, max_length=50)),
                ("station_name", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(db_index=True, max_length=30)),
                ("device_code", models.CharField(db_index=True, max_length=100)),
                ("device_name", models.CharField(max_length=150)),
                ("area", models.CharField(blank=True, max_length=150)),
                ("fault_code", models.CharField(db_index=True, max_length=100)),
                ("fault_description", models.CharField(max_length=500)),
                ("severity", models.CharField(db_index=True, max_length=20)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                (
                    "source_fault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="station_api.devicefaultlog",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["station_code", "device_type", "change_type"],
                        name="st_faultchg_station_type_idx",
                    ),
                    models.Index(
                        fields=["source_fault", "change_type"],
                        name="st_faultchg_source_type_idx",
                    ),
                ],
            },
        ),
    ]
