# Generated by Django 5.2.15 on 2026-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.TextField(blank=True, help_text='Camera description or installation notes.'),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='offline', help_text='Current camera connection status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this camera should be displayed on the monitoring dashboard.'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Legacy/simple online flag. Can be synchronized with status later.'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, help_text='Camera login password, if required.', max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.TextField(blank=True, help_text='RTSP / MJPEG / HLS stream URL for this camera.'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, help_text='Camera login username, if required.', max_length=100),
        ),
    ]
