# Generated by Django 5.2.15 on 2026-07-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_code', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('api_url', models.URLField(blank=True)),
                ('model_path', models.TextField(blank=True)),
                ('confidence_threshold', models.FloatField(default=0.8)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_code'],
            },
        ),
    ]
