# Generated by Django 5.2.15 on 2026-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['id'], 'verbose_name': 'AI model', 'verbose_name_plural': 'AI models'},
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='api_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='AI API URL'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='confidence_threshold',
            field=models.FloatField(default=0.8, verbose_name='信心分數門檻'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='event_type',
            field=models.CharField(choices=[('escalator_fall', '電扶梯人員跌倒'), ('luggage_roll', '大行李箱滾落'), ('large_luggage_intrusion', '大件行李進入設定畫面區域'), ('wheelchair_detected', '辨識輪椅'), ('passenger_loitering', '旅客逾時滯留'), ('crowd_count_abnormal', '人流統計異常'), ('other', '其他')], default='other', max_length=50, verbose_name='對應事件類型'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='模型代碼'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_path',
            field=models.TextField(blank=True, verbose_name='模型路徑'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='模型名稱'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='版本'),
        ),
    ]
