# Generated by Django 5.2.15 on 2026-07-21 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0002_alter_aimodel_options_alter_aimodel_api_url_and_more'),
        ('cameras', '0002_camera_description_camera_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_code', models.CharField(help_text='例如：INF-001', max_length=50, unique=True, verbose_name='推論主機代碼')),
                ('name', models.CharField(help_text='例如：第一月台 AI 推論主機', max_length=100, verbose_name='推論主機名稱')),
                ('base_url', models.URLField(help_text='例如：http://192.168.6.20:8000', max_length=500, unique=True, verbose_name='Base URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟用')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, verbose_name='HTTP Timeout 秒數')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('unknown', 'Unknown'), ('maintenance', 'Maintenance')], db_index=True, default='unknown', max_length=20, verbose_name='主機狀態')),
                ('last_health_at', models.DateTimeField(blank=True, null=True, verbose_name='最後 Health 檢查時間')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最後成功輪詢時間')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='最後錯誤時間')),
                ('last_error', models.TextField(blank=True, verbose_name='最後錯誤訊息')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'Inference host',
                'verbose_name_plural': 'Inference hosts',
                'ordering': ['host_code'],
            },
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='event_type',
            field=models.CharField(choices=[('escalator_fall', '電扶梯跌倒'), ('luggage_roll', '行李滾落'), ('large_luggage_intrusion', '大型行李進入限制區域'), ('wheelchair_detected', '輪椅偵測'), ('passenger_loitering', '旅客逗留過久'), ('crowd_count_abnormal', '人流數量異常'), ('other', '其他')], default='other', max_length=50, verbose_name='對應事件類型'),
        ),
        migrations.CreateModel(
            name='InferenceCameraMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_camera_id', models.CharField(help_text='推論主機 API 回傳的 camera_id，例如 cam_01。', max_length=100, verbose_name='來源 Camera ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟用')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_camera_mappings', to='cameras.camera', verbose_name='Django Camera')),
                ('inference_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_mappings', to='ai_bridge.inferencehost', verbose_name='推論主機')),
            ],
            options={
                'verbose_name': 'Inference camera mapping',
                'verbose_name_plural': 'Inference camera mappings',
                'ordering': ['inference_host__host_code', 'source_camera_id'],
                'constraints': [models.UniqueConstraint(fields=('inference_host', 'source_camera_id'), name='unique_inference_host_source_camera'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('inference_host', 'camera'), name='unique_active_camera_per_inference_host')],
            },
        ),
    ]
