# Generated by Django 5.2.15 on 2026-08-01 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bridge', '0003_inferencehost_alter_aimodel_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceConnectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('reconnect_count', models.PositiveIntegerField(default=0)),
                ('last_imported_inference_id', models.PositiveBigIntegerField(default=0)),
                ('last_source_event_id', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inference_host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_state', to='ai_bridge.inferencehost')),
            ],
        ),
    ]
