# Generated by Django 5.2.15 on 2026-08-19 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('login_background_enabled', models.BooleanField(default=False, verbose_name='啟用登入背景圖片')),
                ('login_background', models.FileField(blank=True, help_text='支援 JPG、JPEG、PNG、WebP；建議 1920x1080 或更高解析度。', upload_to='ui/login/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='登入背景圖片')),
                ('login_overlay_opacity', models.DecimalField(decimal_places=2, default=0.78, help_text='0.00 為透明，1.00 為完全遮蔽；建議 0.65～0.85。', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='背景遮罩透明度')),
                ('login_title', models.CharField(default='通報主機操作員登入', max_length=100, verbose_name='登入頁標題')),
                ('login_subtitle', models.CharField(blank=True, default='請使用授權帳號進入 Dashboard、Monitor Wall 與事件通報管理介面。', max_length=255, verbose_name='登入頁副標題')),
                ('login_footer_text', models.CharField(blank=True, default='KRTC AI CCTV Notification Host V6', max_length=255, verbose_name='登入頁 Footer')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
            ],
            options={
                'verbose_name': '前台介面設定',
                'verbose_name_plural': '前台介面設定',
            },
        ),
    ]
