# Generated by Django 5.2.15 on 2026-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_uiconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="uiconfiguration",
            name="superuser_usb_key_id",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=100,
                verbose_name="USB Key ID",
            ),
        ),
        migrations.AddField(
            model_name="uiconfiguration",
            name="superuser_usb_required",
            field=models.BooleanField(
                default=False, verbose_name="Superuser USB 二次驗證"
            ),
        ),
        migrations.AddField(
            model_name="uiconfiguration",
            name="superuser_usb_token_sha256",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=64,
                verbose_name="USB Token SHA-256",
            ),
        ),
        migrations.AddField(
            model_name="uiconfiguration",
            name="superuser_usb_updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="USB 授權最後更新時間",
            ),
        ),
    ]
