# Generated by Django 5.2.15 on 2026-08-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0003_uiconfiguration_superuser_usb_key_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uiconfiguration",
            name="login_theme",
            field=models.CharField(
                choices=[("dark", "Dark Mode"), ("bright", "Bright Mode")],
                default="dark",
                help_text="Dark Mode 為深色登入框；Bright Mode 為亮色半透明登入框。",
                max_length=20,
                verbose_name="登入框主題",
            ),
        ),
    ]
