# Generated by Django 5.2.15 on 2026-09-30 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0004_uiconfiguration_login_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastEngineeringSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pjsip_executable_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="例如 C:\\krtc-tools\\pjsip\\pjsua.exe",
                        max_length=500,
                        verbose_name="PJSUA 執行檔路徑",
                    ),
                ),
                (
                    "pjsip_local_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="通報主機實際用於 SIP/RTP 通訊的 IPv4 位址。",
                        null=True,
                        protocol="IPv4",
                        verbose_name="PJSIP Local IP",
                    ),
                ),
                (
                    "pjsip_advertise_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="PJSIP 對外宣告的 IPv4 位址；通常與 Local IP 相同。",
                        null=True,
                        protocol="IPv4",
                        verbose_name="PJSIP Advertise IP",
                    ),
                ),
                (
                    "pjsip_local_sip_port_base",
                    models.PositiveIntegerField(
                        default=64882,
                        validators=[
                            django.core.validators.MinValueValidator(1024),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="SIP Port Base",
                    ),
                ),
                (
                    "pjsip_local_rtp_port_base",
                    models.PositiveIntegerField(
                        default=4004,
                        validators=[
                            django.core.validators.MinValueValidator(1024),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="RTP Port Base",
                    ),
                ),
                (
                    "pjsip_port_step",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Port Step",
                    ),
                ),
                (
                    "pjsip_audio_gain_percent",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="PJSIP 播放音量增益百分比；100 表示原始增益。",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Audio Gain (%)",
                    ),
                ),
                (
                    "last_diagnostic_status",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=20,
                        verbose_name="最後診斷狀態",
                    ),
                ),
                (
                    "last_diagnostic_message",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="最後診斷訊息",
                    ),
                ),
                (
                    "last_diagnostic_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="最後診斷時間",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最後修改時間"),
                ),
            ],
            options={
                "verbose_name": "廣播工程設定",
                "verbose_name_plural": "廣播工程設定",
            },
        ),
    ]
