# Generated by Django 5.2.15 on 2026-07-06 11:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0002_camera_description_camera_status_and_more'),
        ('events', '0003_alter_event_options_event_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_code', models.CharField(help_text='例如：AUD-FALL-001', max_length=50, unique=True, verbose_name='Audio Code')),
                ('name', models.CharField(help_text='例如：電扶梯人員跌倒警示廣播', max_length=100, verbose_name='Audio Name')),
                ('audio_type', models.CharField(choices=[('alert', 'Alert'), ('guidance', 'Guidance'), ('warning', 'Warning'), ('test', 'Test'), ('other', 'Other')], default='alert', max_length=20, verbose_name='Audio Type')),
                ('file', models.FileField(upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Audio File')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration Seconds')),
                ('message_text', models.TextField(blank=True, help_text='音檔對應的文字稿或廣播內容', verbose_name='Message Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Audio File',
                'verbose_name_plural': 'Audio Files',
                'ordering': ['audio_code'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_code', models.CharField(help_text='例如：SPK-001、PAO-A1', max_length=50, unique=True, verbose_name='Speaker Code')),
                ('name', models.CharField(help_text='例如：月台區 A1 IP Speaker', max_length=100, verbose_name='Speaker Name')),
                ('station_name', models.CharField(blank=True, help_text='例如：R10 美麗島站', max_length=100, verbose_name='Station Name')),
                ('area', models.CharField(blank=True, help_text='例如：月台區、穿堂層、電扶梯區', max_length=100, verbose_name='Area')),
                ('location_note', models.CharField(blank=True, help_text='設備實際位置補充說明', max_length=255, verbose_name='Location Note')),
                ('ip_address', models.GenericIPAddressField(help_text='IP Speaker / PAO 的 IP 位址', verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(default=80, verbose_name='Port')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('sip', 'SIP'), ('rtsp', 'RTSP'), ('custom', 'Custom')], default='http', max_length=20, verbose_name='Protocol')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('password', models.CharField(blank=True, help_text='PoC 階段暫存。正式版建議改用環境變數或加密儲存。', max_length=100, verbose_name='Password')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Checked At')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Speaker Device',
                'verbose_name_plural': 'Speaker Devices',
                'ordering': ['speaker_code'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(help_text='例如：RULE-FALL-A1', max_length=50, unique=True, verbose_name='Rule Code')),
                ('name', models.CharField(help_text='例如：月台 A1 跌倒事件廣播規則', max_length=100, verbose_name='Rule Name')),
                ('event_type', models.CharField(choices=[('fall_down', '電扶梯人員跌倒'), ('luggage_rolling', '大行李箱滾落'), ('large_luggage_area', '大件行李進入設定畫面區域'), ('wheelchair', '辨識輪椅'), ('overstayed', '旅客逾時滯留'), ('crowd_flow_abnormal', '人流統計異常')], max_length=50, verbose_name='Event Type')),
                ('priority', models.PositiveIntegerField(default=100, help_text='數字越小優先權越高。', verbose_name='Priority')),
                ('auto_broadcast', models.BooleanField(default=True, help_text='是否在事件發生後自動建立廣播紀錄。', verbose_name='Auto Broadcast')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_rules', to='notifications.audiofile', verbose_name='Audio File')),
                ('camera', models.ForeignKey(blank=True, help_text='可選。若不指定，代表此事件類型的通用規則。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_rules', to='cameras.camera', verbose_name='Camera')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_rules', to='notifications.speakerdevice', verbose_name='Speaker Device')),
            ],
            options={
                'verbose_name': 'Broadcast Rule',
                'verbose_name_plural': 'Broadcast Rules',
                'ordering': ['priority', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('playing', 'Playing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('request_payload', models.JSONField(blank=True, help_text='預留後續實際呼叫 Speaker API 時記錄 request。', null=True, verbose_name='Request Payload')),
                ('response_payload', models.JSONField(blank=True, help_text='預留後續實際呼叫 Speaker API 時記錄 response。', null=True, verbose_name='Response Payload')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Requested At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_logs', to='notifications.audiofile', verbose_name='Audio File')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_logs', to='events.event', verbose_name='Event')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_logs', to='notifications.broadcastrule', verbose_name='Broadcast Rule')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_logs', to='notifications.speakerdevice', verbose_name='Speaker Device')),
            ],
            options={
                'verbose_name': 'Broadcast Log',
                'verbose_name_plural': 'Broadcast Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
