# Generated by Django 5.2.15 on 2026-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerdevice',
            name='sip_uri',
            field=models.CharField(blank=True, help_text='例如：sip:4267@192.168.6.120。若使用 MicroSIP 撥號，優先使用此欄位。', max_length=255, verbose_name='SIP URI'),
        ),
    ]
