# Generated by Django 5.2.15 on 2026-07-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_event_updated_at_and_more'),
        ('notifications', '0002_speakerdevice_sip_uri'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='broadcastlog',
            constraint=models.UniqueConstraint(condition=models.Q(('speaker__isnull', False), ('status__in', ['pending', 'playing'])), fields=('speaker',), name='uniq_active_broadcast_per_speaker'),
        ),
    ]
