# Generated by Django 5.2.15 on 2026-07-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_broadcastlog_uniq_active_broadcast_per_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastrule',
            name='event_type',
            field=models.CharField(choices=[('escalator_fall', '電扶梯人員跌倒'), ('luggage_roll', '大行李箱滾落'), ('large_luggage_intrusion', '大件行李進入設定畫面區域'), ('wheelchair_detected', '辨識輪椅'), ('passenger_loitering', '旅客逾時滯留'), ('crowd_count_abnormal', '人流統計異常'), ('other', '其他')], max_length=50, verbose_name='Event Type'),
        ),
    ]
