# Generated by Django 5.2.15 on 2026-08-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_broadcastrule_multi_speakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerdevice",
            name="deployment_state",
            field=models.CharField(
                choices=[
                    ("planned", "Planned / Not Installed"),
                    ("deployed", "Deployed"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                ],
                default="planned",
                help_text="未實體安裝時請維持 Planned；只有 Deployed 才可進入健康監測。",
                max_length=20,
                verbose_name="Deployment State",
            ),
        ),
        migrations.AddField(
            model_name="speakerdevice",
            name="health_monitor_enabled",
            field=models.BooleanField(
                default=False,
                help_text="只有 Deployed 且啟用監測時，探測失敗才會寫入 System Log。",
                verbose_name="Health Monitor Enabled",
            ),
        ),
    ]
